webcontrol/Controllers/PlanetController.cs
using Microsoft.AspNetCore.Mvc;
using webcontrol.Services;

namespace webcontrol.Controllers
{
  
    public class PlanetController : Controller
    {
        private readonly PlanetService _planetService;

        private readonly ILogger<PlanetController> _logger;

        public  PlanetController(PlanetService planetService, ILogger<PlanetController> logger)
        {
            _planetService = planetService;
            _logger = logger;
        }
    
        public IActionResult Index()
        {
            return View();
        }
        //router action
        [BindProperty(SupportsGet = true, Name = "action")]
        public string Name { get; set; }
        
        public IActionResult Mercury()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Earth()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Jupiter()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Mars()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Neptune()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Saturn()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Uranus()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Venus()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }


        //ID
        [Route("hanhtinh/{id:int}")]
        public IActionResult PlanetInfo(int id)
        {
            var planet = _planetService.Where(p => p.Id == id).FirstOrDefault();
            return View("Detail", planet);
        }
    }
}

webcontrol/Views/Planet/Detail.cshtml
@model webcontrol.Models.PlanetModel

<h1>@Model.VnName - @Model.Name</h1>

<div class="card w-50">
    <img src="~/Planet/@(Model.Name).jpg" alt="">
    <div class=" card-body">
        <div class="card-text">
            @Model.Content
        </div>
    <a class="card-link" asp-action="Index">Các hành tinh</a>
    </div>
</div>

webcontrol/Views/Planet/Index.cshtml
@inject webcontrol.Services.PlanetService planetService
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <h1>Các hành tinh trong hệ mặt trời</h1>
    <div class="list-group">
    @foreach (var planet in planetService)
    {
        <a class="list-group-item list-group-item-action" asp.asp-controller="Planet" asp-action="@planet.Name">
            @planet.VnName - @planet.Name
        </a>
    }
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>